os: linux
sudo: required
language: "minimal"
services:
  - docker
env:
  - DOCKER_IMAGE="toliak/bootstrap-cpp"

before_script:
  - docker pull $DOCKER_IMAGE

jobs:
  include:
    - name: "coverage"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/coverage.sh $DOCKER_IMAGE

notifications:
email: false